### ISSUE TITLE
[CI/CD] - Melhoria nos pipelines de CI/CD para gerenciamento de imagens Docker

### ISSUE THREAD

**Issue by diegosneves** [diegosneves/conectar-doacoes#46]
Nesta issue, iremos abordar as modificações nos pipelines de CI/CD para gestão das imagens Docker. Vamos adicionar condições nos workflows de CI (Continuous Integration) para garantir que a construção e envio de imagens Docker para o Docker Hub aconteçam somente quando um PR (Pull Request) for mesclado nas branches `main` e `release/*`. Essas modificações irão melhorar a consistência e segurança do nosso processo de CI/CD.

- [x] **Adicionar Condição no Workflow de CI para o arquivo `ci-prod.yaml`**
   - É necessario modificar o arquivo de workflow `ci-prod.yaml` para adicionar uma condição de validação na etapa `Build and push`. Essa condição irá verificar se um PR para a branch `main` foi mesclado e, somente nesse caso, a construção e envio da imagem Docker será realizada.

```yaml
      - name: Build and push
        id: docker_build
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: diegoneves/conectar-doacoes:latest
          build-args: |
            DB_NAME=${{ env.DB_NAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_USERNAME=${{ env.DB_USERNAME }}
```

- [x] **Adicionar Condição no Workflow de CI para o arquivo `ci-hlg.yaml`**
   - Semelhante ao item anterior, vamos modificar o arquivo de workflow `ci-hlg.yaml` para adicionar uma condição de validação na etapa `Build and push`. Desta vez, a condição deverá verificar se um PR foi mesclado em qualquer branch do tipo `release/*` e, se verdadeiro, a construção e envio da imagem Docker será realizada.

```yaml
      - name: Build and push
        id: docker_build
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/release/*'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: diegoneves/conectar-doacoes:${{ env.BRANCH_NAME }}
          build-args: |
            DB_NAME=${{ env.DB_NAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_USERNAME=${{ env.DB_USERNAME }}
```

Ambas as tarefas acima irão garantir um controle mais refinado sobre nosso processo de CI/CD, aumentando a eficiência e a segurança de nossas operações.
